In [1]:
import pandas as pd

In [3]:
bloomberg_not_include_score_processed = pd.read_csv('../CSR_score/bloomberg_not_include_score_processed.csv')
refinitiv_ESG_score = pd.read_csv('../CSR_score/refinitiv_ESG_score_100.csv')

In [4]:
bloomberg_not_include_score_processed.head()

,ticker,2005,2006,2007,2008,2009,2010,2011,2012,2013,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,CEQP,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,18.4891,24.3436,32.3308,37.4912,51.8660,45.8807,56.4128,59.5011,0.0000,0.0
1,ZEAL,0.0,6.7096,11.6890,11.6890,20.3501,25.7922,29.1922,29.2828,29.2828,...,24.0720,30.3088,30.6508,35.2983,35.2983,34.7752,34.7752,34.3124,38.4971,0.0
2,LOGI,0.0,0.0000,0.0000,29.4337,29.4337,32.1597,32.1597,30.2485,33.4876,...,43.9091,45.9813,47.8926,49.8541,58.4448,65.7680,67.0959,68.9568,70.2545,0.0
3,PTC,0.0,0.0000,26.9088,26.9088,26.9088,26.9088,26.9088,27.7437,30.7313,...,31.8378,29.0313,32.0290,44.1605,48.3754,46.4340,46.9570,53.2039,53.0631,0.0
4,EGLE,0.0,0.0000,0.0000,0.0000,0.0000,26.9088,26.9088,26.9088,26.9088,...,27.9348,27.9348,31.2645,31.2645,31.2645,36.2237,39.2013,37.3906,39.1409,0.0

In [5]:
refinitiv_ESG_score.head()

,ticker,2002,2003,2004,2005,2006,2007,2008,2009,2010,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,000001,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,...,-1.000000,-1.000000,27.908434,32.087866,29.059687,38.335916,46.984385,48.164278,46.837472,-1.0
1,000012,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,13.337063,...,16.855896,17.472804,19.336666,28.562193,30.352233,30.686928,26.445324,29.576761,32.986807,-1.0
2,000021,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,19.898403,25.855248,23.112696,35.455272,43.506165,-1.0
3,000027,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,...,-1.000000,-1.000000,9.285156,10.039419,28.249444,39.075645,31.150010,47.706944,46.812781,-1.0
4,000028,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,23.665338,14.944332,26.608268,25.181559,37.479293,-1.0

In [8]:
common_years = [str(year) for year in range(2005, 2025)]
refinitiv_ESG_score_filtered = refinitiv_ESG_score[['ticker'] + common_years]

merged = bloomberg_not_include_score_processed.merge(refinitiv_ESG_score_filtered, on='ticker', suffixes=('_bloomberg', '_refinitiv'))

for year in common_years:
    col_bloomberg = f"{year}_bloomberg"
    col_refinitiv = f"{year}_refinitiv"

    merged[year] = merged.apply(lambda row: 0 if row[col_bloomberg] == 0 or row[col_bloomberg] == -1 or 
                        row[col_refinitiv] == 0 or row[col_refinitiv] == -1 
                    else row[col_bloomberg] - row[col_refinitiv], axis=1)
    
merged = merged[['ticker'] + common_years]
merged.to_csv('../CSR_score/common_score_ESG_0319.csv', index=False)

In [9]:
common_score_ESG_0319 = pd.read_csv('../CSR_score/common_score_ESG_0319.csv')
common_score_ESG = pd.read_csv('../CSR_score/common_score_ESG.csv')

In [11]:
common_score_ESG_all = pd.concat([common_score_ESG, common_score_ESG_0319], ignore_index=True)
common_score_ESG_all.to_csv('../CSR_score/common_score_ESG_all.csv', index=False)